project:
  type: book

book:
  title: "Dissertation"
  author: "Andrew Murray"
  date: "September 21, 2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format: uncPDF-pdf



